# Generated by Django 5.2.5 on 2025-08-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="quarter",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="match",
            name="quarter_duration",
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name="match",
            name="quarter_end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="timer_status",
            field=models.CharField(
                choices=[
                    ("stopped", "Stopped"),
                    ("running", "Running"),
                    ("paused", "Paused"),
                ],
                default="stopped",
                max_length=10,
            ),
        ),
    ]
