# Generated by Django 5.2.5 on 2025-08-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0002_match_quarter_match_quarter_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="remaining_time_on_pause",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
